# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
	hardware.enableAllFirmware = true;
	boot.extraModulePackages = with config.boot.kernelPackages; [
		broadcom_sta
	];
	boot.blacklistedKernelModules = [
		"b43"
		"bcma"
		"brcmsmac"
		"ssb"
	];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5441f20c-0121-4781-af9f-779965251bfd";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0BBA-5AEB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b074c940-b8b6-4d5b-8174-a18ab1606824"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.config = {
  	permittedInsecurePackages = [
		"broadcom-sta-6.30.223.271-59-6.18.4"
	];	
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
